name: Run Benchmarks
on:
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'
      
      - name: Install
        run: |
          # Install dependencies
          yarn install --immutable

          # Install hyperfine
          wget https://github.com/sharkdp/hyperfine/releases/download/v1.17.0/hyperfine_1.17.0_amd64.deb
          sudo dpkg -i hyperfine_1.17.0_amd64.deb
      
      - name: Run Tests Cold
        run: |
          hyperfine --runs 5 \
          'yarn workspace jest test' \
          'yarn workspace vitest test' \
          'yarn workspace vitest test --isolate=false'

      - name: Run Tests Warm
        run: |
          hyperfine --warmup 1 --runs 5 \
          'yarn workspace jest test' \
          'yarn workspace vitest test' \
          'yarn workspace vitest test --isolate=false'
